apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgBvw0aBEXG7S0pzafVi6xB+terSwt+BjyyXkhD5e9ECOURBQKlwJodu6fTBWA3ytpro+9xsj+h/AZsuu8HPNgREzftrsa2sgy5q9yoRhPLsphN5+tinuGRQUEtmnhL4usAm+0chTCgV2594Nn0TZZNluvZvmfo2N+P1tpk5KhbyeJKV3ms2VfSbOgGIgnD/mVAkabakRwj/yDYjvkZ5x04MwnkUlUtuxx0XxqhomVQ3ZQxzjMoac9zLdBp+0ub/93PF+zniPXhqifZWcWfOdpJBGL23aEPGQR4Q5wfz59S/+yuEOLb5YXTbq2qNEzQd/mDG8waAvYnfQp1wlrnI1RRRLIzbchMeGrItPWNxqunagxu7pYXhI1TlS34nbRtEmeZ4PsQIO4i8pw6kbwrg+qhaxflD0Xzi1cbNRwlkmWJuFl55jv/KpxikoBbDqFmn1swEa8Eq6B0HaHO80trDAde5+TRBjq4Vv9F5QNk0wYtEh2GvTvnQrNBPpu7SxHsir7xrnwayX56V9VCbMOFc+e//zzc+dCNk81ecciCMR80T+o66p38Re+Uki9NWaAWz9fDc9g20NrKyBVEHUm0jUl34MKiq7KE7YtkM+0JFOC2DWjcBzsr72jk8OqiNWErZm2aHGMDTRVhJ2fttpXWYplDw2shDBck1+kORmSHnzJnHYCCH4ukG+tSMTq8NAmqd4BDmDRh4XphnF1EI9jYoD57RddCYWhXIN0iF
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database

